export const CLICK_GENERATE = 'CLICK_GENERATE';
export const DISPLAY_TWEET = 'DISPLAY_TWEET';

export const FETCH_TWEETS = 'FETCH_TWEETS';
export const FETCH_TWEETS_REJECTED = 'FETCH_TWEETS_REJECTED';
export const FETCH_TWEETS_FULFILLED = 'FETCH_TWEETS_FULFILLED';

export const SAVE_TWEET = 'SAVE_TWEET';
export const SAVE_TWEET_REJECTED = 'SAVE_TWEET_REJECTED';
export const SAVE_TWEET_FULFILLED = 'SAVE_TWEET_FULFILLED';

export const FETCH_FAVORITES = 'FETCH_FAVORITES';
export const FETCH_FAVORITES_REJECTED = 'FETCH_FAVORITES_REJECTED';
export const FETCH_FAVORITES_FULFILLED = 'FETCH_FAVORITES_FULFILLED';

export const DELETE_TWEET = 'DELETE_TWEET';
export const DELETE_TWEET_REJECTED = 'DELETE_TWEET_REJECTED';
export const DELETE_TWEET_FULFILLED = 'DELETE_TWEET_FULFILLED';

export const CLICK_LOGIN = 'CLICK_LOGIN';
export const CLICK_SIGNUP = 'CLICK_SIGNUP';
export const CLICK_LOGOUT = 'CLICK_LOGOUT';

export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_FULFILLED = 'LOGIN_USER_FULFILLED';
export const LOGIN_USER_REJECTED = 'LOGIN_USER_REJECTED';

export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNUP_USER_FULFILLED = 'SIGNUP_USER_FULFILLED';
export const SIGNUP_USER_REJECTED = 'SIGNUP_USER_REJECTED';

export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGOUT_USER_FULFILLED = 'LOGOUT_USER_FULFILLED';
export const LOGOUT_USER_REJECTED = 'LOGOUT_USER_REJECTED';
